---
title: "Does Posting a Photo on Strava Get You More Kudos?"
author: "Annie Busath"
format: html
---

## Introduction

I am an avid runner and I recently introduced my husband to Strava. We went to the gym one day and he stopped to take a selfie to add to his Strava post. He said that he gets more Kudos (the equivalent to a 'like') when he adds a photo. After I made fun of him for that statement, I was wondering how true that is? As two people with few followers (48 for me and less for him on his new account), is there really a difference? What about a strava post invites more kudos from my friends? As someone who unfortunately seeks validation from others, I wanted to find out what exactly does make a more kudos-worthy post?

## Motivating Question

#### Do Strava activites with photos receive more kudos than activities without photos?

## Ethics

Strava has a very user friendly API with clear documentation on their website. In order to ethically use this, I had to create an application. Strava used to have an open api where anyone could call methods without authentication. This created an uncontrollable and untrackable load on their servers. This caused them to "close" their API to give them more control over who accesses the API and how they do it. To abide by their new guidelines to avoid this, I registered an 'application' which essentially is my permission to access the API. Additionally to avoid overloading their systems, I made sure to only run the code every 15 minutes since it was scraping such a large set of data.

## Steps

### 1. Register a Strava Application

To access the API, I registered an application at:

[Strava API Settings](https://www.strava.com/settings/api)

This process generates several credentials needed to authenticate requests, including:

- Client ID  
- Client Secret  
- Access Token  

The access token allows my program to make requests on behalf of my Strava account.

## 2. Authenticate with the Strava API

Using the authentication documentation provided by Strava, I generated an access token that allowed my script to retrieve activity data. For data privacy, I stored this in a personal credentials file that I called in.

The authentication guide can be found here:

[Strava Authentication Documentation](https://developers.strava.com/docs/authentication/)

## 3. Retrieve Activity Data

Using Python and the `requests` library, I called the Strava endpoint:

`/athlete/activities`

This endpoint returns information about the activities associated with the authenticated athlete.

Since Strava only returns a limited number of activities per request, I implemented **pagination** to retrieve all available activities.

## 4. Extract Relevant Variables

From each activity returned by the API, I extracted several features relevant to my question:

- Activity ID  
- Activity name  
- Distance  
- Moving time  
- Total elevation gain  
- Kudos count  
- Photo count  
- Whether the activity contained a photo  
- Activity date  

These variables allow me to compare engagement (kudos) across activities with and without photos.

## Overview of the Final Dataset

After collecting the data, I constructed a dataset where each row represents a single Strava activity from my personal account.

**Dataset size**

- Observations (activities): 783  
- Features: 8  

### Data Dictionary

| Variable    | Description |
|------------|-------------|
| activity_id | Unique identifier for the activity |
| name       | Name given to the activity |
| date       | Date the activity occurred |
| distance   | Distance of the activity (miles) |
| moving_time| Total moving time (minutes) |
| kudos_count| Number of kudos received |
| photo_count| Number of photos attached to the activity |
| has_photo  | Indicator variable (1 = photo present, 0 = no photo) |

## Data Cleaning and Processing

The raw API data required only minimal cleaning. The main transformations included:

- Creating the `has_photo` indicator variable for later analysis  
- Converting distance from meters to miles  
- Converting date to YYYY-MM-DD format  
- Exporting the final dataset to a CSV file for analysis  

## Limitations of the Data

The main limitation for this dataset is that I can only call the data from my personal account which provides insights that may not generalize to other users.

## Code Repository

The full code used to collect this dataset can be found here:
[Strava Authentication Documentation](https://developers.strava.com/docs/authentication/)
[Github Strava Repository](https://github.com/abusath8/strava_kudos_project)